name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and read file
          run: 
            echo "my first github actions job"
            ls -ltra
            cat README.md
        
 # executing 3rd part library   
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt
          